cache: bundler
language: ruby

# We will support old rubies as long as we can. It's important that people
# with badly out-of-date systems can still measure how bad they are.
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7

script:
  - bundle exec rubocop
  - bundle exec rspec
sudo: false
